MobileStore/Areas/Admin/Controllers/FooterController.cs
using Models.DAO.Repository;
using Models.EF;
using System.Web.Mvc;

namespace MobileStore.Areas.Admin.Controllers
{
    public class FooterController : BaseController
    {
        private UnitOfWork _unitOfWork = new UnitOfWork();

        // GET: Admin/Footer
        public ActionResult Index()
        {
            return View(_unitOfWork._FooterRepo.SelectById("MAIN"));
        }

        [HttpPost, ValidateAntiForgeryToken, ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id, Content, Status")] Footer footer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork._FooterRepo.Update(footer);
                    _unitOfWork.Save();
                    SetAlert("Cập nhật thành công.", Common.Enum.EAlertMessage.Success);
                    return RedirectToAction("Index");
                }
                catch
                {
                    SetAlert("Có lỗi xảy ra khi cập nhật! Vui lòng thử lại.", Common.Enum.EAlertMessage.Danger);
                }
            }
            return View("Index", footer);
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

MobileStore/Controllers/CartController.cs
using Models.ViewModels;
using Models.DAO.Repository;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace MobileStore.Controllers
{
    public class CartController : Controller
    {
        private UnitOfWork _unitOfWork = new UnitOfWork();

        public async Task<ActionResult> Index()
        {
            var cart = _unitOfWork._CartRepo.GetCart(this);

            var ViewModel = new CartViewModel
            {
                CartItems = await cart.GetCartItemsAsync(),
                CartTotal = await cart.GetTotalAsync()
            };

            return View(ViewModel);
        }

        public async Task<ActionResult> AddToCart(int productId)
        {
            var cart = _unitOfWork._CartRepo.GetCart(this);
            await cart.AddToCart(productId);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> RemoveFromCart(int productId)
        {
            var cart = _unitOfWork._CartRepo.GetCart(this);

            var results = new CartRemoveViewModel
            {
                Status = await cart.RemoveFromCart(productId),
                CartItems = await cart.GetCartItemsAsync(),
                ItemCount = await cart.GetCountAsync(),
                CartTotal = await cart.GetTotalAsync()
            };

            var list = JsonConvert.SerializeObject(results, Formatting.None, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return Content(list, "application/json");
        }

        [HttpPost]
        public async Task<ActionResult> ChangeQuantityFromCart(int productId, bool flag, int quantity)
        {
            var cart = _unitOfWork._CartRepo.GetCart(this);
            CartRemoveViewModel results;
            if (flag && await _unitOfWork._ProductRepo.CheckCurrentQuantity(productId, quantity))
            {
                results = new CartRemoveViewModel
                {
                    Status = true
                };
            }
            else
            {
                results = new CartRemoveViewModel
                {
                    ItemCount = await cart.ChangeQuantity(productId, flag),
                    CartItems = await cart.GetCartItemsAsync(),
                    CartTotal = await cart.GetTotalAsync(),
                };
            }

            var list = JsonConvert.SerializeObject(results, Formatting.None, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return Content(list, "application/json");
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

MobileStore/Controllers/MobileController.cs
using Models.DAO.Repository;
using System.Web.Mvc;
using Models.ViewModels;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace MobileStore.Controllers
{
    public class MobileController : Controller
    {
        private UnitOfWork _unitOfWork = new UnitOfWork();

        [OutputCache(Duration = 600, VaryByParam ="*")]
        public async Task<ActionResult> Index(string metaTitle = "", int page = 1, string orderBy = "")
        {
            ViewBag.SortOrder = orderBy;
            ViewBag.MetaTitle = metaTitle;
            if (Request.IsAjaxRequest())
            {
                return Json(await LoadProducts(metaTitle, orderBy, page, 10), JsonRequestBehavior.AllowGet);
            }
            ViewBag.HasPaging = string.IsNullOrEmpty(metaTitle) ? true : false;
            ViewBag.BrandList = await _unitOfWork._ProductCategoryRepo.sp_GetListCategoryNameAsync();
            return View(await LoadProducts(metaTitle, orderBy, page));
        }

        [ChildActionOnly, OutputCache(Duration = 86400, VaryByParam = "None")]
        public PartialViewResult _Banner()
        {
            return PartialView(_unitOfWork._SlideRepo.GetSlideByPosition(Common.Enum.EDatabase.ESlidePosition.PhoneTop));
        }

        public async Task<IEnumerable<ProductBriefViewModel>> LoadProducts(string metaTitle, string orderBy, int page, int pageSize = 9)
        {
            return await _unitOfWork._ProductRepo.SelectProductByFilterHasPagingAsync(metaTitle, orderBy, page, pageSize);
        }

        [OutputCache(Duration = 600, VaryByParam ="key")]
        public async Task<ActionResult> Search(string key)
        {
            ViewBag.Key = key;
            return View(await _unitOfWork._ProductRepo.ListProductByKeywordAsync(key));
        }

        public async Task<ActionResult> LoadProductName(string key)
        {
            var list = JsonConvert.SerializeObject(await _unitOfWork._ProductRepo.ListNameByKeywordAsync(key), Formatting.None, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return Content(list, "application/json");
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

MobileStore/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Thông báo";
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}

<h4>@ViewBag.Message</h4>

MobileStore/Views/Shared/_AdminArea.cshtml
@model IEnumerable<Models.ViewModels.NavigationViewModel>

@if (Model != null)
{
    <div id="admin-area">
        <div class="container">
            <div class="row">
                @foreach (var menu in Model)
                {
                    <a href="@menu.Link" target="@menu.Target" title="@menu.Text">
                        @Html.Raw(menu.Icon) @menu.Text
                    </a>
                }
            </div>
        </div>
    </div>
}

MobileStore/Views/Shared/_Footer.cshtml
@model string

    @Html.Raw(Model)


<div id="copy-right">
    Copyright&copy; 2017 Anh Đỗ Mobile. All rights reserved. Developed by Anh Đỗ Dev.
</div>

MobileStore/Views/Shared/_Header.cshtml
@model Models.ViewModels.CartStatusToHeaderViewModel
@{
    IEnumerable<Models.ViewModels.NavigationViewModel> TopMenu = ViewBag.TopMenu;
}
<div class="col-xs-9 logo">
    <a href="@Url.Action("Index", "Home")" title="Về trang chủ AnhDo Mobile">
        <h1>anhdo<span class="dotcom">mobile</span></h1>
    </a>
</div>
<div id="CartStatus" class="col-xs-3 right">
    <a class="cart" title="Giỏ hàng của bạn">
        <i class="fa fa-shopping-bag"></i>
        @if (Model.ItemCount > 0)
        {
            <span class="total">@Model.ItemCount</span>
            <div class="info">
                @foreach (var item in Model.CartItems)
                {
                    <!-- row -->
                    <div class="row">
                        <img class="col-xs-3" src="@item.Image" alt="@item.Name" title="@item.Name">
                        <div class="col-xs-9">
                            <h2 class="name">@item.Name (@item.Count)</h2>
                            <span class="price">
                                @(item.Price.ToString("N0"))đ
                            </span>
                        </div>
                    </div>
                }
                <!-- ./row -->
                <div class="row">
                    <div class="col-xs-12">
                        Tổng:<strong class="price" id="total-status">@Model.CartTotal.ToString("N0")đ</strong>
                        <span class="btn btn-xs btn-success" onclick="window.location.href= '@Url.Action("Index", "Cart")'">Thanh toán</span>
                    </div>
                </div>
            </div>
        }
    </a>
    @Html.Partial("_LoginPartial", TopMenu)
</div>

<script id="cart-st-info-template" type="x-tmpl-mustache">
    <div class="row">
        <img class="col-xs-3" src="{{ProductImage}}" alt="{{ProductName}}" title="{{ProductName}}">
        <div class="col-xs-9">
            <h2 class="name">{{ProductName}} ({{Count}})</h2>
            <span class="price">
                {{ProductPrice}}
            </span>
        </div>
    </div>
</script>

<script id="cart-st-total-template" type="x-tmpl-mustache">
    <div class="row">
        <div class="col-xs-12">
            Tổng:<strong class="price" id="total-status">{{CartTotal}}</strong>
            <span class="btn btn-xs btn-success" onclick="window.location.href= '@Url.Action("Index", "Cart")'">Thanh toán</span>
        </div>
    </div>
</script>

MobileStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | AnhDo Mobile</title>
    <meta name="keywords" content="anhdo, anh do, anhdomobile, anhdo mobile, dien thoai di dong, smartphone tai ha noi, apple, samsung, sony, oppo" />
    <meta name='description' content='Cửa hàng điện thoại di động, smartphone, apple, samsung chính hãng tại hà nội, giá tốt, dịch vụ khách hàng được yêu thích nhất.' />
    <meta name='copyright' content='Công ty Cổ phần Bán lẻ Kỹ thuật số AnhDo' />
    <meta name='author' content='Công ty Cổ phần Bán lẻ Kỹ thuật số AnhDo' />
    <meta name="GENERATOR" content="Công ty Cổ phần AnhDo Mobile" />
    <link rel="icon" href="~/Assets/Common/images/icon/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="~/Assets/Common/images/icon/favicon.png" type="image/x-icon" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/bundles/st-site-core")

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-103634770-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments) };
        gtag('js', new Date());

        gtag('config', 'UA-103634770-1');
    </script>


</head>
<body>

    @{Html.RenderAction("_AdminArea", "Home");}

    <header id="header" class="container">
        @{Html.RenderAction("_Header", "Home");}
    </header>

    <nav id="main-nav" class="navbar navbar-inverse navbar-static-top">
        @{Html.RenderAction("_Navigation", "Home");}
    </nav>

    <section id="main">
        @RenderSection("BelowMain", false)
        <div class="wrapper container">
            @RenderBody()
        </div>
    </section>
    <footer id="footer">

        @{Html.RenderAction("_Footer", "Home");}

    </footer>

    <a id="back-to-top"></a>
    @Scripts.Render("~/bundles/sc-site-core")

    @RenderSection("scripts", required: false)

    <script src="~/Scripts/removeSomee.js"></script>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/59d8a0fec28eca75e46249ca/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
</body>
</html>

MobileStore/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | AnhDo Mobile</title>
    <meta name="keywords" content="anhdo, anh do, anhdomobile, anhdo mobile, dien thoai di dong, smartphone tai ha noi, apple, samsung, sony, oppo" />
    <meta name='description' content='Cửa hàng điện thoại di động, smartphone, apple, samsung chính hãng tại hà nội, giá tốt, dịch vụ khách hàng được yêu thích nhất.' />
    <meta name='copyright' content='Công ty Cổ phần Bán lẻ Kỹ thuật số AnhDo' />
    <meta name='author' content='Công ty Cổ phần Bán lẻ Kỹ thuật số AnhDo' />
    <meta name="GENERATOR" content="Công ty Cổ phần AnhDo Mobile" />
    <link rel="icon" href="~/Assets/Common/images/icon/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="~/Assets/Common/images/icon/favicon.png" type="image/x-icon" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    @Styles.Render("~/bundles/st-site-core")
    @Styles.Render("~/bundles/st-site-account-core")


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-103634770-1"></script>
    <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-103634770-1');
    </script>

</head>
<body>
    <header id="header" class="container">
        @{Html.RenderAction("_Header", "Home");}
    </header>

    <nav id="main-nav" class="navbar navbar-inverse navbar-static-top">
        @{Html.RenderAction("_Navigation", "Home");}
    </nav>
    <div class="container">
        <div class="row" style="margin: 10px auto;">
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/sc-site-core")
    @Scripts.Render("~/bundles/sc-site-account-core")
    @RenderSection("scripts", false)

    <script src="~/Scripts/removeSomee.js"></script>

    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
        var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
        (function () {
            var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/59d8a0fec28eca75e46249ca/default';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
        })();
    </script>
    <!--End of Tawk.to Script-->
</body>
</html>

MobileStore/Views/Shared/_Navigation.cshtml
@model IEnumerable<Models.ViewModels.NavigationViewModel>

<div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="@Url.Action("Index", "Home")" class="active navbar-brand" title="Trang chủ AnhDo Mobile">
            <i class="fa fa-home fa-fw"></i> Home
        </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
            @foreach (var menu in Model)
            {
                <li><a href="@menu.Link" target="@menu.Target" title="@menu.Text">@Html.Raw(menu.Icon) @menu.Text</a></li>
            }
        </ul>
        <form action="@Url.Action("Search", "Mobile")" class="navbar-form navbar-right form-search">
            <div class="form-group">
                <div class="input-group">
                    @Html.TextBox("key", null, new { @id = "search-box", @class = "form-control input-sm", @placeholder = "Nhập từ khóa...", @required="required" })
                    <div class="input-group-btn">
                        <button class="btn btn-default btn-sm" type="submit">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div id="wrap-suggestion" class="bg-white hide">

            </div>
        </form>
    </div>
</div>

<script id="suggestion-template" type="x-tmpl-mustache">
    <!-- item -->
    <a href="/dien-thoai-{{MetaTitle}}-{{Id}}" class="clearfix" title="{{Name}}">
        <img class="col-xs-3 img-responsive padding-zero" src="{{Image}}" alt="{{Name}}">
        <div class="col-xs-9">
            <h3 class="name">{{Name}}</h3>
            <div class="discount">
                {{{PromotionPrice}}}
            </div>
            <div class="normal">
                {{{Price}}}
            </div>
        </div>
    </a>
</script>