MobileStore/Areas/Admin/Controllers/ProductCategoryController.cs
using System.Web.Mvc;
using Models.EF;
using System.Net;
using Common;
using Common.Enum;
using Models.DAO.Repository;

namespace MobileStore.Areas.Admin.Controllers
{
    public class ProductCategoryController : BaseController
    {
        private UnitOfWork _unitOfWork = new UnitOfWork();

        public ActionResult Index()
        {
            return View(_unitOfWork._ProductCategoryRepo.Select());
        }

        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            string[] categoryIds = form["categoryId"].Split(',');

            foreach (string item in categoryIds)
            {
                try
                {
                    foreach (var product in _unitOfWork._ProductRepo.Select(p=>p.CategoryID.ToString() == item))
                    {
                        _unitOfWork._ProductRepo.Delete(product);
                    }
                    _unitOfWork._ProductCategoryRepo.Delete(int.Parse(item));
                }
                catch { }
            }
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            ParentIdsDropDownList();
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, ParentID, DisplayOrder, MetaTitle, Status")] ProductCategory category)
        {
            if (ModelState.IsValid)
            {
                if (_unitOfWork._ProductCategoryRepo.CheckNameIsExists(category.Name))
                    ModelState.AddModelError("Name", "Tên danh mục sản phẩm đã tồn tại");
                else
                {
                    try
                    {
                        _unitOfWork._ProductCategoryRepo.Insert(category);
                        _unitOfWork.Save();
                        SetAlert("Tạo mới danh mục <b>" + category.Name + "</b> thành công.", EAlertMessage.Success);
                        return RedirectToAction("Index");
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Có lỗi xảy ra khi tạo mới danh mục! Vui lòng thử lại.");
                    }
                }
            }
            ParentIdsDropDownList(category.ParentID);
            return View(category);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ProductCategory category = _unitOfWork._ProductCategoryRepo.SelectById(id.Value);
            if (category == null)
            {
                ViewBag.ErrorMessage = "Danh mục sản phẩm không tồn tại.";
                return View("Error");
            }

            ParentIdsDropDownList(category.ParentID, category.Id);
            return View(category);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, FormCollection form)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            ProductCategory category = _unitOfWork._ProductCategoryRepo.SelectById(id.Value);
            if (category == null)
            {
                ViewBag.ErrorMessage = "Danh mục sản phẩm không tồn tại.";
                return View("Error");
            }
            string oldName = category.Name.ToUpper();

            if (TryUpdateModel(category, new string[] { "Id", "Name", "ParentID", "DisplayOrder", "MetaTitle", "Status" }))
            {
                if (_unitOfWork._ProductCategoryRepo.CheckNameIsExists(category.Name) && oldName != category.Name.Trim().ToUpper())
                {
                    ModelState.AddModelError("Name", "Tên danh mục sản phẩm đã tồn tại");
                }
                else
                {
                    try
                    {
                        _unitOfWork._ProductCategoryRepo.Update(category);
                        _unitOfWork.Save();
                        SetAlert("Cập nhật thông tin danh mục <b>" + category.Name + "</b> thành công.", EAlertMessage.Success);
                        return RedirectToAction("Index");
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Có lỗi xảy ra khi cập nhật thông tin! Vui lòng thử lại.");
                    }
                }
            }
            ParentIdsDropDownList(category.ParentID, category.Id);
            return View(category);
        }

        public string ConvertMetaTitle(string name)
        {
            return Convertion.ToUnsignString(name);
        }

        public void ParentIdsDropDownList(int? selected = null, int? id = null)
        {
            ViewBag.ParentID = new SelectList(_unitOfWork._ProductCategoryRepo.GetDropDownLists(id), "Id", "Name", selected);
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

MobileStore/Areas/Admin/Views/ProductCategory/Create.cshtml
@model Models.EF.ProductCategory

@{
    ViewBag.Title = "Thêm mới danh mục sản phẩm";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Thêm mới danh mục sản phẩm</h4>
        <hr />
        
        @Html.Partial("_ProductCategoryForm")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> Tạo mới</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



MobileStore/Areas/Admin/Views/ProductCategory/Edit.cshtml
@model Models.EF.ProductCategory

@{
    ViewBag.Title = "Cập nhật thông tin danh mục sản phẩm";
}

@using (Html.BeginForm())
{    
    <div class="form-horizontal">
        <h3>Cập nhật thông tin danh mục sản phẩm</h3>
        <hr />
        @Html.HiddenFor(model => model.Id)

        @Html.Partial("_ProductCategoryForm")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> Lưu lại</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



MobileStore/Areas/Admin/Views/ProductCategory/Index.cshtml
@model IEnumerable<Models.EF.ProductCategory>

@{
    ViewBag.Title = "Danh sách danh mục sản phẩm";
}

<div class="row">
    <div class="col-lg-12">
        <h4 class="page-header">Danh sách danh mục sản phẩm</h4>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body">
                @using (Html.BeginForm("Delete", "ProductCategory"))
                {
                    <div class="col-md-8 row">
                        <button type="submit" onclick="return confirm('Bạn có chắc là muốn xóa không')" class="btn btn-danger"><i class="fa fa-trash"></i> Delete</button>
                        <a href="@Url.Action("Create")" class="btn btn-default"><i class="fa fa-plus"></i> Create New</a>
                    </div>
                    <div class="col-md-4 row pull-right">
                        <input type="text" onkeyup="filterTable(this)" class="form-control" placeholder="Nhập từ khóa...">
                    </div>
                    <div class="clearfix"></div>
                    if (TempData["AlertMessage"] != null)
                    {
                        <div id="alertBox" class="alert alert-@TempData["AlertType"] text-center">
                            @Html.Raw(TempData["AlertMessage"])
                        </div>
                    }

                    @Html.Partial("_ListForm")
                }
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

MobileStore/Areas/Admin/Views/ProductCategory/_ListForm.cshtml
@model IEnumerable<Models.EF.ProductCategory>
<table class="table table-striped table-bordered table-hover" style="margin-top:15px;">
    <thead>
        <tr>
            <th>@Html.CheckBox("chkDeleteAll", new { id = "chkDeleteAll" })</th>
            <th class="pointer" onclick="sortMenu(1)">@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.ParentID)</th>
            <th class="pointer" onclick="sortMenu(3)">@Html.DisplayNameFor(model => model.DisplayOrder)</th>
            <th class="pointer" onclick="sortMenu(4)">@Html.DisplayNameFor(model => model.Status)</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="list-data">
        @foreach (var category in Model)
        {

            <tr>
                <td>@Html.CheckBox("categoryId", htmlAttributes: new { @class = "chkFieldId", value = category.Id })</td>
                <td class="name">@category.Name</td>

                <td>
                    @if (category.ParentID.HasValue)
                {
                    @Model.Where(x => x.Id == category.ParentID).SingleOrDefault().Name;
                }
            </td>
            <td>@category.DisplayOrder</td>
            <td>@(category.Status ? "Hiển thị" : "Ẩn" )</td>
            <td><a class="" href="@Url.Action("Edit", new { id = category.Id })"><i class="fa fa-edit"></i> Edit</a></td>
        </tr>
        }
    </tbody>
</table>


MobileStore/Areas/Admin/Views/ProductCategory/_ProductCategoryForm.cshtml

@model Models.EF.ProductCategory


@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.AntiForgeryToken()
<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.ParentID, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.ParentID, null, "Không có", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ParentID, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.MetaTitle, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.MetaTitle, new { htmlAttributes = new { @class = "form-control", @onclick = "convertMetaTitle('/ProductCategory/ConvertMetaTitle/')" } })
        @Html.ValidationMessageFor(model => model.MetaTitle, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <div class="checkbox">
            @Html.RadioButtonFor(model => model.Status, false) Ẩn
            @Html.RadioButtonFor(model => model.Status, true) Hiển thị
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
